{{- range $key, $val := .Values.namespaces }}
{{- with $key }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: "{{ $key }}-alert-config"
  namespace: {{ $key }}
  labels:
    alertmanagerConfig: {{ $key }}-alert-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: {{ $.Values.defaultReceiver.name }}
  {{ if not $val.useOnlyDefaultReceiver }}
  routes:
  {{- range $receiver := $val.receivers.others }}
    - receiver: {{ .name }}
      groupBy: ['job']
      groupWait: 30s
      groupInterval: 5m
      repeatInterval: 4h
  {{- end }}
  {{- end }}
  receivers:
  - name: {{ $.Values.defaultReceiver.name }}
    webhookConfigs:
    - url: {{ $.Values.defaultReceiver.webhookURL | quote }}
  {{ if not $val.useOnlyDefaultReceiver }}
  {{- range $receiver := $val.receivers.others }}
  - name: {{ .name }}
    webhookConfigs:
    - url: {{ .webhookURL | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}